theme: jekyll-theme-cayman

title2024: SERIAL 2024
description2024: 5th Workshop on Scalable and Resilient Infrastructures for Distributed Ledgers
conference_location2024: Québec City, Québec, Canada
conference_date2024: 7 - 11 November 2024
conference_colocated2024: Middleware 2024
conference_colocated_url2024: https://middleware-conf.github.io/2024/
top_navs2024:
  - title: "Call For Paper"
    anchor: "#call-for-papers"
    new_tab: false
  - title: "Submission"
    anchor: "#submission-guidelines"
    new_tab: false
  - title: "Important dates"
    anchor: "#important-dates"
    new_tab: false
  - title: "Committees"
    anchor: "#committees"
    new_tab: false
  - title: "SERIAL 2020"
    anchor: "/serial20/"
    new_tab: true

# title2023: SERIAL 2023
# description2023: 6th Workshop on Scalable and Resilient Infrastructures for Distributed Ledgers
# conference_location2023: Québec City, Québec, Canada
# conference_date2023: 7 - 11 November 2024
# conference_colocated2023: Middleware 2024
# conference_colocated_url2023: https://middleware-conf.github.io/2024/
# top_navs2023:
#   - title: "Call For Paper"
#     anchor: "#call-for-papers"
#   - title: "Submission"
#     anchor: "#submission-guidelines"
#   - title: "Important dates"
#     anchor: "#important-dates"
#   - title: "Committees"
#     anchor: "#committees"
#   - title: "SERIAL 2024"
#     anchor: "https://serial.ibr.cs.tu-bs.de/serial20/"
